name: Build

on: [push, pull_request]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install required build toolchain
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y libarchive-tools
        
      - name: Configure fontawesome
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: .npmrc
          contents: |
            @fortawesome:registry=https://npm.fontawesome.com/
            //npm.fontawesome.com/:_authToken=${{ secrets.FONTAWESOME_TOKEN }}
          write-mode: overwrite

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          ADBLOCK: true

      - name: Get commit message
        run: echo "::set-output name=message::$(git log --no-merges -1 --oneline)"

      - name: Build the app
        run: yarn ci-build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          MAC_CERTS: ${{ secrets.mac_certs }}
          MAC_CERTS_PASSWORD: ${{ secrets.mac_certs_password }}

          RELEASE: ${{ startsWith(github.ref, 'refs/tags/v') }}
